[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm-error.log

[program:nginx]
process_name=%(program_name)s
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx-error.log

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work redis --sleep=3 --tries=3
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-worker.log

[program:laravel-scheduler]
process_name=%(program_name)s
command=php /var/www/html/artisan schedule:run
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/var/log/supervisor/laravel-scheduler.log
stderr_logfile=/var/log/supervisor/laravel-scheduler-error.log
